---
- name: Fetch Cisco router startup config
  hosts: cisco
  gather_facts: false

  vars:
    output_file: "/home/student/demo/{{ inventory_hostname }}_config.txt"

  tasks:
    - name: Get startup configuration
      cisco.ios.ios_command:
        commands: show startup-config
      register: startup_config

    - name: Save startup config to local file
      ansible.builtin.copy:
        content: "{{ startup_config.stdout[0] }}"
        dest: "{{ output_file }}"